import React from 'react';
import { ShieldAlert, BookOpenCheck } from 'lucide-react';

const TajweedResults = ({ result }) => {
    if (!result) return null;

    // Both html from Gradio and the custom word_details are available.
    // The user requested the exact same output as the Gradio project, which is provided in result.html

    return (
        <div className="bg-white p-6 rounded-2xl shadow-sm border border-gray-100 flex flex-col font-arabic" dir="rtl">
            <h3 className="text-xl font-bold text-[#044D29] font-amiri mb-6 flex items-center gap-2 border-b pb-4">
                <BookOpenCheck size={24} className="text-[#D4AF37]" />
                نتيجة اختبار التجويد والصفات
            </h3>


            {/* Phoneme & Sifat Raw HTML inject (Hidden per user request) */}
            <div className="tajweed-gradio-html-container hidden">
                <div dangerouslySetInnerHTML={{ __html: result.html }} />
            </div>

            {/* If we also want to show the Word-by-Word summary generated by the engine */}
            {result.word_details && result.word_details.length > 0 && (
                <div className="mt-8 pt-6 border-t border-gray-200">
                    <h4 className="text-lg font-bold text-[#044D29] mb-4">تفصيل التلاوة:</h4>
                    <div className="flex flex-wrap gap-3 text-2xl font-amiri leading-[2.5]">
                        {result.word_details.map((wd, i) => (
                            <span
                                key={i}
                                className={`px-2 py-1 rounded-md transition-colors ${wd.has_error ? 'cursor-help' : 'text-[#044D29]'}`}
                                title={wd.has_error ? wd.error_descriptions.join(' | ') : 'نطق صحيح'}
                                dangerouslySetInnerHTML={{ __html: wd.html_content || wd.text }}
                            />
                        ))}
                    </div>
                </div>
            )}
        </div>
    );
};

export default TajweedResults;
